version: '3.8'

services:
  backend:
    build:
      context: ./ # Usamos el mismo contexto porque backend y frontend comparten la carpeta
    command: node index.js
    ports:
      - "3000:3000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}

  frontend:
    build:
      context: ./ # Usamos el mismo contexto porque backend y frontend comparten la carpeta
    command: npm run build
    ports:
      - "8080:80"
    depends_on:
      - backend
